spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bootex?useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: aaron
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

# App Properties
aaron:
  app:
    jwtSecret: aaronSecretKeyihihihguiudy
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 8640000